ambionics/phpggc

- phpggc
> Use /usr/bin/env to resolve php

- gadgetchains/Magento/SQLI/1/chain.php
- gadgetchains/Magento/SQLI/1/gadgets.php
- lib/PHPGGC/GadgetChain.php
- lib/PHPGGC/GadgetChain/SqlInjection.php
Details on this gadget chain are here...
https://maxchadwick.xyz/blog/using-cve-2016-4010-gadget-chain-in-magento-1
> Add Magento 1 SQLi gadget chain

- README.md
- gadgetchains/Symfony/RCE2/chain.php
- gadgetchains/Symfony/RCE2/gadgets.php
- gadgetchains/Symfony/RCE3/chain.php
- gadgetchains/Symfony/RCE3/gadgets.php
Hello. Look this one. I hope it will be useful.
> Symfony Framework 2.3.42 <= 2.8.32 (latest of 2.x now) RCE __destruct POP chain

- README.md
Sorry, forgot to edit README.md in the last pull request
> Update README.md with Magento/FW1

- README.md
- gadgetchains/CodeIgniter4/RCE/1/chain.php
- gadgetchains/CodeIgniter4/RCE/1/gadgets.php
This adds a CodeIgniter 4 RCE chain. I have tested it on the latest version 4.0.0-beta.1.
Earlier alpha versions might work as well with a slight modification
> Add CodeIgniter 4 RCE gadget chain

- gadgetchains/WordPress/Guzzle/RCE/2/chain.php
- gadgetchains/WordPress/Guzzle/RCE/2/gadgets.php
Modify a guzzle RCE 1 gadgetchain.
> add a guzzle RCE 2 gadgetchain

- README.md
- gadgetchains/CodeIgniter4/RCE/1/chain.php
- gadgetchains/CodeIgniter4/RCE/1/gadgets.php
Seems like they changed some stuff in recent versions of CodeIgniter4. This should fix the gadget chain.
Tested on 4.0.2 and 4.0.3.
> Fix codeigniter4 chain

- gadgetchains/ZendFramework/RCE/4/chain.php
- gadgetchains/ZendFramework/RCE/4/gadgets.php
This GC based on ZendFramework/RCE1 and works on PHP 7.
> Add ZendFramework/RCE gadget chain

- gadgetchains/CodeIgniter4/RCE/2/chain.php
- gadgetchains/CodeIgniter4/RCE/2/gadgets.php
Added a (very) small fix so the chain works for the latest version.
I tested against 4.0.0-rc.4 so it should not break for previous CodeIgniter4 versions.
> Changed chain for CodeIgniter4 v4.0.4

- README.md
- gadgetchains/Laravel/RCE/7/chain.php
- gadgetchains/Laravel/RCE/7/gadgets.php
Gadget Chain for the latest version of laravel. 
I will eventually test for previous versions.
> Laravel RCE7 8.16.1

- gadgetchains/Smarty/FD/1/chain.php
- gadgetchains/Smarty/FD/1/gadgets.php
Hi there,
Just adding a smarty FileDeletion payload that has been hanging around for a while. Tested against a few CMS using smarty and it's working fine.
> Added Smarty FD Payload

- gadgetchains/Yii2/RCE/2/chain.php
- gadgetchains/Yii2/RCE/2/gadgets.php
Hello phpggc maintainers 👋,
this is a gadget chain we found for the Yii2 PHP framework.
If you have any further questions or improvements let me know.
> Another Yii2 RCE gadget chain

- gadgetchains/Symfony/RCE/5/chain.php
- gadgetchains/Symfony/RCE/5/gadgets.php
New gadgets for latest version of symfony (v5.2.x).
> Added Symfony RCE5

- gadgetchains/Doctrine/FW/2/chain.php
- gadgetchains/Doctrine/FW/2/gadgets.php
Hi there,
This chain tested on different 2.х versions, PHP7/8. I hope it will be useful.
> Doctrine <= 2.8.5 / FileWrite `__destruct` chain

- gadgetchains/CakePHP/RCE/1/chain.php
- gadgetchains/CakePHP/RCE/1/gadgets.php
- gadgetchains/CakePHP/RCE/2/chain.php
- gadgetchains/CakePHP/RCE/2/gadgets.php
If you have any questions, please contact me through 3300162791@qq.com.
> Add CakePHP gadgets

- gadgetchains/CodeIgniter4/RCE/3/chain.php
- gadgetchains/CodeIgniter4/RCE/3/gadgets.php
> Added CodeIgniter4 RCE3

- gadgetchains/PHPSecLib/RCE/1/chain.php
- gadgetchains/PHPSecLib/RCE/1/gadgets.php
Hi there,
This chain tested on different 2.0.x versions. Generates warnings and notices.
> phpseclib 2.0.0 <= 2.0.34 / RCE `__destruct` chain

- README.md
- gadgetchains/Kohana/FR/1/chain.php
- gadgetchains/Kohana/FR/1/gadgets.php
Add Kohana File read gadget.
https://github.com/kohana/core/blob/3.3/master/classes/Kohana/View.php#L232
Possible RCE, because of the include() function:
https://github.com/kohana/core/blob/3.3/master/classes/Kohana/View.php#L62
Update README.md gadgets list.
> Add Kohana FR1

- gadgetchains/Laravel/RCE/11/gadgets.php
Hello,
Two properties were removed.
Thank you.
> Making Laravel/RCE11 smaller.

- README.md
- gadgetchains/Bitrix/RCE/chain.php
- gadgetchains/Bitrix/RCE/gadgets.php
Hi,
This is a chain for core of the Bitrix [product line](https://www.1c-bitrix.ru/products/cms/). An extremely popular product in the CIS countries, which is used to create simple sites, portals, shops and CRMs. According [to w3techs statistics](https://w3techs.com/technologies/history_overview/content_management), the product is used by 1.1% of sites in the world.
> Bitrix 17.x.x <= 22.0.300 / RCE `__destruct chain`

- README.md
- gadgetchains/ZendFramework/RCE/5/chain.php
- gadgetchains/ZendFramework/RCE/5/gadgets.php
> Zendframework 2.0.1 RCE/5

- README.md
- gadgetchains/Symfony/RCE/6/chain.php
- gadgetchains/Symfony/RCE/6/gadgets.php
> Symfony3.4 RCE/6

- README.md
- gadgetchains/CodeIgniter4/RCE/5/chain.php
- gadgetchains/CodeIgniter4/RCE/5/gadgets.php
- gadgetchains/CodeIgniter4/RCE/6/chain.php
- gadgetchains/CodeIgniter4/RCE/6/gadgets.php
the chains for codeigniter requires predis, I test on 4.1.3 version
> Add chains on Ci4.1.3

- gadgetchains/Phing/FD/1/chain.php
- gadgetchains/Phing/FD/1/gadgets.php
- gadgetchains/SwiftMailer/FD/2/chain.php
- gadgetchains/SwiftMailer/FD/2/gadgets.php
- gadgetchains/SwiftMailer/FR/1/chain.php
- gadgetchains/SwiftMailer/FR/1/gadgets.php
- gadgetchains/Yii/RCE/2/chain.php
- gadgetchains/Yii/RCE/2/gadgets.php
Hi, back again.
Phing/fd1:
Swiftmailer/fr1:
Swiftmailer/fd2:
yii/rce2:
> Some Chains

- gadgetchains/Snappy/FD/1/chain.php
- gadgetchains/Snappy/FD/1/gadgets.php
Hello,
I would like to add my [Snappy](https://github.com/KnpLabs/snappy) gadget chain to PHPGGC.
> PHP library allowing thumbnail, snapshot or PDF generation from a url or a html page. Wrapper for wkhtmltopdf/wkhtmltoimage 
- Library name:
- Snappy
- KnpLabs / snappy
- URL:
- https://github.com/KnpLabs/snappy
Below is the responsible code.
File: <span style="color:red">src/Knp/Snappy/AbstractGenerator.php</span>
```php
<?php
...
abstract class AbstractGenerator implements GeneratorInterface, LoggerAwareInterface
{
use LoggerAwareTrait;
/**
* @var array
*/
public $temporaryFiles = [];
...
public function __destruct()
{
$this->removeTemporaryFiles();
}
...
/**
* Removes all temporary files.
*
* @return void
*/
public function removeTemporaryFiles()
{
foreach …
```
> Snappy: Added FD/1, which targets Snappy versions <= 1.4.2

- README.md
- gadgetchains/CodeIgniter4/FR/1/chain.php
- gadgetchains/CodeIgniter4/FR/1/gadgets.php
- gadgetchains/CodeIgniter4/RCE/2/chain.php
- gadgetchains/CodeIgniter4/RCE/3/chain.php
Update CodeIgniter4 versions.
Add CodeIgniter4 File read gadget.
https://github.com/codeigniter4/CodeIgniter4/blob/v4.3.6/system/View/Cells/Cell.php#L119
Possible RCE, because of the include() function:
https://github.com/codeigniter4/CodeIgniter4/blob/v4.3.6/system/View/Cells/Cell.php#L110
Update README.md gadgets list.
> Add CodeIgniter4 FR1

- gadgetchains/CodeIgniter4/FD/2/chain.php
- gadgetchains/CodeIgniter4/FD/2/gadgets.php
I would like to add my [CodeIgniter4](https://github.com/codeigniter4/CodeIgniter4) gadget chain to PHPGGC.
> Open Source PHP Framework (originally from EllisLab) .
- Framework name:
- CodeIgniter4
- codeigniter4 / CodeIgniter4
- URL:
- [https://github.com/codeigniter4/CodeIgniter4](https://github.com/codeigniter4/CodeIgniter4)
Below is the responsible code.
File: <span style="color:red">system/Publisher/Publisher.php</span>
```php
<?php
...
class Publisher extends FileCollection
{
...
/**
* Removes a directory and all its files and subdirectories.
*/
private static function wipeDirectory(string $directory): void
{
if (is_dir($directory)) {
// Try a few times in case of lingering locks
$attempts = 10;
while ((bool) $attempts && ! delete_files($directory, true, false, …
```
> CodeIgniter4: Added FD/2, which targets CodeIgniter4 versions <= 4.3.7

- gadgetchains/Magento2/FD/2/chain.php
- gadgetchains/Magento2/FD/2/gadgets.php
Hello, 
A file delete chain that looks like the first one but uses different classes.
:)
> Codespace potential space guacamole p9pvg946g97h744p

- gadgetchains/Laravel/RCE/17/chain.php
- gadgetchains/Laravel/RCE/17/gadgets.php
- gadgetchains/Laravel/RCE/18/chain.php
- gadgetchains/Laravel/RCE/18/gadgets.php
Hi,
I'm adding Laravel GC under RCE.
Regards,
ahmadshauqi
> Adding new Laravel GadgetChain

- gadgetchains/Laravel/RCE/19/chain.php
- gadgetchains/Laravel/RCE/19/gadgets.php
Hello :)
A gadget chain on Laravel that make RCE.
Thank you.
Maxime
> [Laravel] RCE19 : 10.34

- README.md
the link currently returns a 404
> update pharggc paper link

- README.md
Hi @cfreal!
Pushing this improvement to the `README` to add more examples in the Docker context.
- Using `--test-payload`
- Generating phar / polyglot files
Best
> docs: improve docker usage

- gadgetchains/Laravel/RCE/21/chain.php
- gadgetchains/Laravel/RCE/21/gadgets.php
> add Laravel/RCE21 5.1.*

- lib/PHPGGC.php
- lib/PHPGGC/Enhancement/PublicAttributes.php
- lib/PHPGGC/Enhancement/PublicProperties.php
https://github.com/ambionics/phpggc/issues/195
> PublicProperties enhancement
